### PR TITLE
Add wayland support

### PR DESCRIPTION
**Pull request by SergioRibera**
If you use the library from wayland it is very likely that you will not get good results, with this PR I intend to solve that problem, I am using smithay because it is the easiest way to work with wayland and as a first integration I think it is great.

> [!IMPORTANT]
> The only thing that could be a problem is the definition of the raw_handler because wayland doesn't really offer an option for this, I have manipulated this to create a handler, but I don't think it will work completely.
> And also to know if the monitor is primary or not, I have not seen how to get that information, but I imagine it is possible.

### CODE REVIEW

**Review by nashaofu — APPROVED** [review]

**Comment by nashaofu** [comment]
MacOS CI failed https://github.com/nashaofu/display-info/actions/runs/7926253156/job/21680059058?pr=30

**Comment by SergioRibera** [comment]
Ok, in a while I'll check the problem and upload a change

**Comment by SergioRibera** [comment]
Problem solved, for some reason I had put the `PartialEq`

**Comment by nashaofu** [comment]
@SergioRibera `is_primary`  has not been implemented

**Comment by SergioRibera** [comment]
@nashaofu Yup, I didn't implement it because I couldn't find a way to make wayland give me that information, if I find a way I will do another PR

**Comment by SergioRibera** [comment]
> 
> Maybe the coordinates of the primary display is `0,0`
> 
I think it would not apply in all cases, for example, my primary display is not at 0x0 because on the left I have my display

**Comment by nashaofu** [comment]
Get

**Pull request merged**
